wso2/kubernetes-microgateway

- helm/microgateway/confs/logstash/logstash.conf
- helm/microgateway/logging/init.sh
- helm/microgateway/templates/microgateway-deployment.yaml
- Fix incorrect path for logs in microgateway-deployemnt
- Change logstash configuration to parse logs
- Fix issue where standard error is not redirected to the log file
> Fix logstash configuration

- README.md
- helm/microgateway/README.md
- Quick start guide is moved into the helm chart foler.
- Added main README
> Adding main README.md

- helm/microgateway/README.md
- Change incorrect references of `WSO2 Identity Server` to `WSO2 API Micorgateway`
- Fix a broken link to Kubernetes documentation for setting up a cluster.
> Document changes requested for readme.md

- helm/microgateway/confs/bin/ballerina
- helm/microgateway/logging/init.sh
- helm/microgateway/templates/microgateway-ballerina.yaml
- helm/microgateway/templates/microgateway-bin.yaml
- helm/microgateway/templates/microgateway-deployment.yaml
- helm/microgateway/templates/microgateway-prometheus-exporter-conf.yaml
- helm/microgateway/templates/microgateway-prometheus-servicemonitor.yaml
- helm/microgateway/values.yaml
Add support for JMX monitoring.
> Add support for JMX monitoring

- CHANGELOG.md
- helm/choreo-connect/README.md
- helm/choreo-connect/values.yaml
> Update release date for 1.0.0.1

- CHANGELOG.md
- helm/choreo-connect/README.md
- helm/choreo-connect/templates/_helpers.tpl
- helm/choreo-connect/templates/adapter-deployment.yaml
- helm/choreo-connect/templates/gateway-runtime-deployment.yaml
- helm/choreo-connect/templates/serviceaccount.yaml
- helm/choreo-connect/values.yaml
This is required to run deployments in OpenShift
Redo https://github.com/wso2/kubernetes-microgateway/commit/a78db77ec961fba11831be5198cdbe39384c5392
Samples: https://gist.github.com/renuka-fernando/31237ac71476af21d8319622004d2634
> Assign service account name to the deployments

- CHANGELOG.md
> Update master branch with Choreo Connect v1.0.0 

- helm/choreo-connect/README.md
> Update master for 1.0.0.1 Release

- CHANGELOG.md
- helm/choreo-connect/Chart.yaml
- helm/choreo-connect/README.md
- helm/choreo-connect/templates/_helpers.tpl
- helm/choreo-connect/templates/adapter-deployment.yaml
- helm/choreo-connect/templates/config-toml-configmap.yaml
- helm/choreo-connect/values.yaml
Resolve https://github.com/wso2/kubernetes-microgateway/issues/32
```yaml
apim:
controlPlane:
hostName: am.wso2.com
serviceName: wso2am-single-node-am-service.apim
eventListeners: []
trafficManagers: []
```
```toml
[enforcer.throttling]
enableGlobalEventPublishing = true
jmsConnectionProviderURL = "amqp://admin:admin@carbon/carbon?brokerlist='tcp://wso2am-single-node-am-service.apim:5672'"
[enforcer.throttling.publisher]
username = "admin"
password = "$env{tm_admin_pwd}"
[[enforcer.throttling.publisher.URLGroup]]
receiverURLs = ["tcp://wso2am-single-node-am-service.apim:9611"]
authURLs = ["ssl://wso2am-single-node-am-service.apim:9711"]
[controlPlane]
enabled = true
serviceURL = "https://wso2am-single-node-am-service.apim:9443/"
username = "admin"
password = "$env{cp_admin_pwd}" …
```
> Support multiple Control Plane and Traffic Manager instances

- CHANGELOG.md
- helm/choreo-connect/Chart.yaml
- helm/choreo-connect/README.md
- helm/choreo-connect/templates/_helpers.tpl
- helm/choreo-connect/templates/adapter-deployment.yaml
- helm/choreo-connect/templates/config-toml-configmap.yaml
- helm/choreo-connect/values.yaml
> Update master for 1.0.0-2 Release

- helm/choreo-connect/templates/adapter-grpc-probe-script-configmap.yaml
- helm/choreo-connect/templates/enforcer-grpc-probe-script-configmap.yaml
fix https://github.com/wso2/kubernetes-microgateway/issues/40
> [1.0.x] Using loopback IP address instead of localhost in gRPC health probe

- helm/choreo-connect/templates/adapter-grpc-probe-script-configmap.yaml
- helm/choreo-connect/templates/enforcer-grpc-probe-script-configmap.yaml
$subject
fix https://github.com/wso2/kubernetes-microgateway/issues/38
> [1.1.x] Using loopback IP address instead of localhost in gRPC health probe

- helm/choreo-connect/templates/adapter-grpc-probe-script-configmap.yaml
- helm/choreo-connect/templates/enforcer-grpc-probe-script-configmap.yaml
> Merge 1.1.x into master

- CHANGELOG.md
- helm/choreo-connect/Chart.yaml
- helm/choreo-connect/README.md
$subject
Tested with CC standalone mode
> Update chart version as 1.0.0-3

- CHANGELOG.md
- helm/choreo-connect/Chart.yaml
- helm/choreo-connect/README.md
$subject
Tested with CC Standalone mode
> Update chart version as 1.1.0-2

- CHANGELOG.md
- helm/choreo-connect/Chart.yaml
- helm/choreo-connect/README.md
- helm/choreo-connect/templates/_helpers.tpl
- helm/choreo-connect/templates/gateway-runtime-deployment.yaml
- helm/choreo-connect/values.yaml
port https://github.com/wso2/kubernetes-microgateway/pull/47
> [1.0.x] Router Heap Dump Support

- CHANGELOG.md
- helm/choreo-connect/Chart.yaml
- helm/choreo-connect/README.md
- helm/choreo-connect/templates/adapter-deployment.yaml
- helm/choreo-connect/templates/gateway-runtime-deployment.yaml
- helm/choreo-connect/templates/router-ingress.yaml
- helm/choreo-connect/templates/router-service.yaml
- helm/choreo-connect/values.yaml
$subject
For more info plz refer to the issues this PR resolves
Resolves #52 #53
> [1.1.x] Expose HTTP port of the Router and automountServiceAccountToken configurable

- CHANGELOG.md
- helm/choreo-connect/Chart.yaml
- helm/choreo-connect/README.md
- helm/choreo-connect/templates/adapter-deployment.yaml
- helm/choreo-connect/templates/gateway-runtime-deployment.yaml
- helm/choreo-connect/templates/router-ingress.yaml
- helm/choreo-connect/templates/router-service.yaml
- helm/choreo-connect/values.yaml
port https://github.com/wso2/kubernetes-microgateway/pull/56
> [1.0.x] Expose HTTP port of the Router and automountServiceAccountToken configurable

- CHANGELOG.md
- helm/choreo-connect/README.md
- helm/choreo-connect/templates/adapter-deployment.yaml
- helm/choreo-connect/templates/gateway-runtime-deployment.yaml
- helm/choreo-connect/values.yaml
Add `apiArtifactsMountEmptyDir` and `dropinsMountEmptyDir`configs
Fixes: #62 #64
> [1.1.x] Add `apiArtifactsMountEmptyDir` and `dropinsMountEmptyDir`configs

- CHANGELOG.md
- helm/choreo-connect/README.md
- helm/choreo-connect/templates/adapter-deployment.yaml
- helm/choreo-connect/templates/gateway-runtime-deployment.yaml
- helm/choreo-connect/values.yaml
Add `apiArtifactsMountEmptyDir` and `dropinsMountEmptyDirconfigs`
Fixes: #63 #65
> [1.0.x] Add `apiArtifactsMountEmptyDir` and `dropinsMountEmptyDir` configs

- helm/choreo-connect/Chart.yaml
- helm/choreo-connect/README.md
> [1.0.x] Update Helm chart version

- helm/choreo-connect/Chart.yaml
- helm/choreo-connect/README.md
> [1.1.x] Update Helm chart version

- helm/choreo-connect/Chart.yaml
- helm/choreo-connect/README.md
> Update master branch

- CHANGELOG.md
- helm/choreo-connect/Chart.yaml
- helm/choreo-connect/README.md
- helm/choreo-connect/templates/gateway-runtime-deployment.yaml
$subject
fix https://github.com/wso2/kubernetes-microgateway/issues/74
> [1.1.x] Fix error applying Router backendCaCerts

- CHANGELOG.md
- helm/choreo-connect/Chart.yaml
- helm/choreo-connect/README.md
- helm/choreo-connect/templates/gateway-runtime-deployment.yaml
$subject
fix https://github.com/wso2/kubernetes-microgateway/issues/76
> [1.0.x] Fix error applying Router backendCaCerts

- helm/choreo-connect/README.md
- helm/choreo-connect/templates/NOTES.txt
- helm/choreo-connect/templates/_helpers.tpl
- helm/choreo-connect/templates/adapter-deployment.yaml
- helm/choreo-connect/templates/gateway-runtime-deployment.yaml
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves #79
> Fix: spelling/key mistakes

- helm/choreo-connect/README.md
- helm/choreo-connect/templates/NOTES.txt
- helm/choreo-connect/templates/_helpers.tpl
- helm/choreo-connect/templates/adapter-deployment.yaml
- helm/choreo-connect/templates/gateway-runtime-deployment.yaml
Port https://github.com/wso2/kubernetes-microgateway/pull/80
> [1.1.x] Fix: spelling/key mistakes

- helm/choreo-connect/README.md
- helm/choreo-connect/templates/NOTES.txt
- helm/choreo-connect/templates/_helpers.tpl
- helm/choreo-connect/templates/adapter-deployment.yaml
- helm/choreo-connect/templates/gateway-runtime-deployment.yaml
> Update master branch from 1.1.x

- helm/choreo-connect/templates/config-toml-configmap.yaml
Fix https://github.com/wso2/kubernetes-microgateway/issues/83
> [1.1.x] Read TM password from env var and disable skipSSLVerification in CP

- helm/choreo-connect/templates/config-toml-configmap.yaml
Fix [github.com/wso2/kubernetes-microgateway#83](https://github.com/wso2/kubernetes-microgateway/issues/88)
Port https://github.com/wso2/kubernetes-microgateway/issues/88
> [1.0.x] Read TM password from env var and disable skipSSLVerification in CP

- helm/choreo-connect/templates/config-toml-configmap.yaml
> Update master branch with 1.1.x

- helm/choreo-connect/values.yaml
$subject
close https://github.com/wso2/kubernetes-microgateway/issues/84
> Add a sample for applying external file as the config

- helm/choreo-connect/values.yaml
port https://github.com/wso2/kubernetes-microgateway/pull/92
> Update master with 1.1.x

- CHANGELOG.md
- helm/choreo-connect/Chart.yaml
- helm/choreo-connect/README.md
- helm/choreo-connect/templates/_helpers.tpl
- helm/choreo-connect/values.yaml
$subject and prepare for release
Fix #99
> [1.0.x] Mount files to truststore with a manual name

- CHANGELOG.md
- helm/choreo-connect/Chart.yaml
- helm/choreo-connect/README.md
- helm/choreo-connect/templates/_helpers.tpl
- helm/choreo-connect/values.yaml
$subject and prepare for release.
Fix https://github.com/wso2/kubernetes-microgateway/issues/97
> [1.1.x] Mount files to truststore with a manual name

- CHANGELOG.md
- helm/choreo-connect/README.md
- helm/choreo-connect/templates/adapter-deployment.yaml
- helm/choreo-connect/templates/gateway-runtime-deployment.yaml
- helm/choreo-connect/values.yaml
Fix https://github.com/wso2/kubernetes-microgateway/issues/101 and update README with config updates.
> [1.0.x] Fix readiness probe in Gateway Runtime

- CHANGELOG.md
- helm/choreo-connect/README.md
- helm/choreo-connect/templates/adapter-deployment.yaml
- helm/choreo-connect/templates/gateway-runtime-deployment.yaml
- helm/choreo-connect/values.yaml
Fix https://github.com/wso2/kubernetes-microgateway/issues/103 and update README with config updates.
> [1.1.x] Fix readiness probe in Gateway Runtime

- CHANGELOG.md
- helm/choreo-connect/values.yaml
> [1.0.x] Remove unused env var `enforcer_admin_pwd`

- CHANGELOG.md
- helm/choreo-connect/values.yaml
> [1.1.x] Remove unused env var `enforcer_admin_pwd`
